apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lgtm-stack.name" . }}-ds-loki
  labels:
    {{- include "lgtm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-read:3100
        version: 1
        editable: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
            # TODO: tenant value from config
            httpHeaderValue1: "tenant1"
